### ISSUE TITLE
Getting errors when using in workflow

### ISSUE THREAD

**Issue by KingScooty** [TrellisCommerce/vercel-lighthouse-score-action#1]
I've just tried to use this action in a basic post deploy workflow(following the install instructions), but i'm getting quite a few errors. 

```yml
  post_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Vercel Preview URL Lighthouse Audit
        uses: TrellisCommerce/vercel-lighthouse-score-action@1.0.1
```

Does this still work out the box? Or are there some steps to follow to get it working?

<img width="882" alt="image" src="https://user-images.githubusercontent.com/610869/222281803-be31db8c-0398-448d-be4f-c710cc115dac.png">
